"""trivial3

Revision ID: 990db0844728
Revises: 191b892bb787
Create Date: 2019-06-18 05:25:39.256337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990db0844728'
down_revision = '191b892bb787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('answerer_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'answerer_name')
    # ### end Alembic commands ###
